apiVersion: batch/v1
kind: CronJob
metadata:
  name: api-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: api-cronjob
            image: 780546410701.dkr.ecr.ap-south-1.amazonaws.com/demo:latest
            command: ["sh", "-c", "curl -s http://localhost:8999/api >> /mnt/logs/app.log"]
            volumeMounts:
            - name: log-volume
              mountPath: /mnt/logs
          restartPolicy: OnFailure
          volumes:
          - name: log-volume
            emptyDir: {}

